on:
  pull_request:
  push:
    branches:
      - main
name: gmon test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build & Format
        run: ./gmon.sh format
      - name: Check changes
        run: |
          if ! git diff --quiet || ! git diff --staged --quiet; then
            echo "Changes detected"
            uname -a
            git diff
            git diff --staged
            exit 1
          fi
      - run: ./gmon.sh test
